<?xml version="1.0"?>

<cruisecontrol xsl:version="1.0"
               xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:for-each select="/projects/project">
    <xsl:variable name="srcdir">
      <xsl:choose>
        <xsl:when test="srcdir">
          <xsl:value-of select="srcdir"/>
        </xsl:when>
        <xsl:otherwise>
          <xsl:value-of select="@name"/>
        </xsl:otherwise>
      </xsl:choose>
    </xsl:variable>
    <project name="{@name}">
      <bootstrappers>
	<currentbuildstatusbootstrapper 
	    file="logs/{@name}/currentbuildstatus.txt"/>
      </bootstrappers>
      <modificationset>
        <xsl:for-each select="repo-dependency">
	  <filesystem folder="/eng/cruisecontrol/.maven/repository/{.}"/>
	</xsl:for-each>
	<cvs localworkingcopy="src/{$srcdir}"/>
      </modificationset>
      <schedule>
	<maven
	    mavenscript="/eng/pkg/maven/bin/maven"
	    projectfile="src/{$srcdir}/project.xml"
	    goal="{goal}"/>
      </schedule>
      <log dir="logs/{@name}">
      </log>
      <publishers>
	<currentbuildstatuspublisher 
	    file="logs/{@name}/currentbuildstatus.txt"/>
	<htmlemail
	    mailhost="localhost"
	    returnaddress="cruisecontrol@domain.name"
	    returnname="Cruise Control"
	    logdir="logs/{@name}"
	    css="/eng/pkg/cruisecontrol/reporting/jsp/css/cruisecontrol.css"
	    xsldir="/eng/pkg/cruisecontrol/reporting/jsp/xsl"
	    reportsuccess="always"
	    spamwhilebroken="yes">
	  <xsl:if test="remote-project">
	    <xsl:attribute name="skipusers">true</xsl:attribute>
	    <always address="developers@domain.name"/>
	  </xsl:if>
          <!-- map 'User' to address when generated by the filesystem plugin -->
          <map alias="User" address="developers@domain.name"/>
	</htmlemail>
      </publishers>
      <dateformat format="dd/MM/yyyy HH:mm:ss"/>
    </project>
  </xsl:for-each>
</cruisecontrol>
